controller_manager:
    ros__parameters:
        update_rate: 100
        use_sim_time: true

    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
        type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
    ros__parameters:
        right_wheel_names: ["wheel1_joint", "wheel2_joint"]
        left_wheel_names: ["wheel3_joint", "wheel4_joint"]

        wheel_seperation: 0.21
        wheels_per_side: 2
        wheel_radius: 0.05

        wheel_separation_multiplier: 1.05
        left_wheel_radius_multiplier: 1.05
        right_wheel_radius_multiplier: 1.05

        publish_rate: 60
        odom_frame_id: odom
        base_frame_id: base_link

        # pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
        # twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

        enable_odom_tf: true

        use_stamped_vel: false

        linear.x.has_velocity_limits: true
        linear.x.has_acceleration_limits: true
        linear.x.has_jerk_limits: false
        linear.x.max_velocity: 5.0
        linear.x.min_velocity: -5.0
        linear.x.max_acceleration: 5.0
        linear.x.max_jerk: 0.0
        linear.x.min_jerk: 0.0

        angular.z.has_velocity_limits: true
        angular.z.has_acceleration_limits: true
        angular.z.has_jerk_limits: false
        angular.z.max_velocity: 5.0
        angular.z.min_velocity: -5.0
        angular.z.max_acceleration: 4.0
        angular.z.min_acceleration: -4.0
        angular.z.max_jerk: 0.0
        angular.z.min_jerk: 0.0
